package notas;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioNotas", targetNamespace = "http://notas/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioNotas {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClaveUso", targetNamespace = "http://notas/", className = "notas.GetClaveUso")
    @ResponseWrapper(localName = "getClaveUsoResponse", targetNamespace = "http://notas/", className = "notas.GetClaveUsoResponse")
    @Action(input = "http://notas/ServicioNotas/getClaveUsoRequest", output = "http://notas/ServicioNotas/getClaveUsoResponse")
    public String getClaveUso();

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws ServicioNotasException
     */
    @WebMethod
    @RequestWrapper(localName = "addNota", targetNamespace = "http://notas/", className = "notas.AddNota")
    @ResponseWrapper(localName = "addNotaResponse", targetNamespace = "http://notas/", className = "notas.AddNotaResponse")
    @Action(input = "http://notas/ServicioNotas/addNotaRequest", output = "http://notas/ServicioNotas/addNotaResponse", fault = {
        @FaultAction(className = ServicioNotasException.class, value = "http://notas/ServicioNotas/addNota/Fault/ServicioNotasException")
    })
    public void addNota(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws ServicioNotasException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws ServicioNotasException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNotas", targetNamespace = "http://notas/", className = "notas.GetNotas")
    @ResponseWrapper(localName = "getNotasResponse", targetNamespace = "http://notas/", className = "notas.GetNotasResponse")
    @Action(input = "http://notas/ServicioNotas/getNotasRequest", output = "http://notas/ServicioNotas/getNotasResponse", fault = {
        @FaultAction(className = ServicioNotasException.class, value = "http://notas/ServicioNotas/getNotas/Fault/ServicioNotasException")
    })
    public List<String> getNotas(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ServicioNotasException
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws ServicioNotasException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNota", targetNamespace = "http://notas/", className = "notas.GetNota")
    @ResponseWrapper(localName = "getNotaResponse", targetNamespace = "http://notas/", className = "notas.GetNotaResponse")
    @Action(input = "http://notas/ServicioNotas/getNotaRequest", output = "http://notas/ServicioNotas/getNotaResponse", fault = {
        @FaultAction(className = ServicioNotasException.class, value = "http://notas/ServicioNotas/getNota/Fault/ServicioNotasException")
    })
    public String getNota(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws ServicioNotasException
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws ServicioNotasException
     */
    @WebMethod
    @RequestWrapper(localName = "removeNota", targetNamespace = "http://notas/", className = "notas.RemoveNota")
    @ResponseWrapper(localName = "removeNotaResponse", targetNamespace = "http://notas/", className = "notas.RemoveNotaResponse")
    @Action(input = "http://notas/ServicioNotas/removeNotaRequest", output = "http://notas/ServicioNotas/removeNotaResponse", fault = {
        @FaultAction(className = ServicioNotasException.class, value = "http://notas/ServicioNotas/removeNota/Fault/ServicioNotasException")
    })
    public void removeNota(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws ServicioNotasException
    ;

}
