
package notas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioNotasImplService", targetNamespace = "http://notas/", wsdlLocation = "http://localhost:9998/notas?wsdl")
public class ServicioNotasImplService
    extends Service
{

    private final static URL SERVICIONOTASIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICIONOTASIMPLSERVICE_EXCEPTION;
    private final static QName SERVICIONOTASIMPLSERVICE_QNAME = new QName("http://notas/", "ServicioNotasImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9998/notas?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIONOTASIMPLSERVICE_WSDL_LOCATION = url;
        SERVICIONOTASIMPLSERVICE_EXCEPTION = e;
    }

    public ServicioNotasImplService() {
        super(__getWsdlLocation(), SERVICIONOTASIMPLSERVICE_QNAME);
    }

    public ServicioNotasImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIONOTASIMPLSERVICE_QNAME, features);
    }

    public ServicioNotasImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICIONOTASIMPLSERVICE_QNAME);
    }

    public ServicioNotasImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIONOTASIMPLSERVICE_QNAME, features);
    }

    public ServicioNotasImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioNotasImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioNotas
     */
    @WebEndpoint(name = "ServicioNotasImplPort")
    public ServicioNotas getServicioNotasImplPort() {
        return super.getPort(new QName("http://notas/", "ServicioNotasImplPort"), ServicioNotas.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioNotas
     */
    @WebEndpoint(name = "ServicioNotasImplPort")
    public ServicioNotas getServicioNotasImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://notas/", "ServicioNotasImplPort"), ServicioNotas.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIONOTASIMPLSERVICE_EXCEPTION!= null) {
            throw SERVICIONOTASIMPLSERVICE_EXCEPTION;
        }
        return SERVICIONOTASIMPLSERVICE_WSDL_LOCATION;
    }

}
