
package ejercicio2_2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StringConversion", targetNamespace = "http://ejercicio2_2/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StringConversion {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     * @throws ExceptionConversion
     */
    @WebMethod(operationName = "string2int")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "string2int", targetNamespace = "http://ejercicio2_2/", className = "ejercicio2_2.String2Int")
    @ResponseWrapper(localName = "string2intResponse", targetNamespace = "http://ejercicio2_2/", className = "ejercicio2_2.String2IntResponse")
    @Action(input = "http://ejercicio2_2/StringConversion/string2intRequest", output = "http://ejercicio2_2/StringConversion/string2intResponse", fault = {
        @FaultAction(className = ExceptionConversion.class, value = "http://ejercicio2_2/StringConversion/string2int/Fault/ExceptionConversion")
    })
    public int string2Int(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws ExceptionConversion
    ;

}
