
package ejercicio2_2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StringConversionImplService", targetNamespace = "http://ejercicio2_2/", wsdlLocation = "http://localhost:8080/tutorial-soap/stringConversion?wsdl")
public class StringConversionImplService
    extends Service
{

    private final static URL STRINGCONVERSIONIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException STRINGCONVERSIONIMPLSERVICE_EXCEPTION;
    private final static QName STRINGCONVERSIONIMPLSERVICE_QNAME = new QName("http://ejercicio2_2/", "StringConversionImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/tutorial-soap/stringConversion?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STRINGCONVERSIONIMPLSERVICE_WSDL_LOCATION = url;
        STRINGCONVERSIONIMPLSERVICE_EXCEPTION = e;
    }

    public StringConversionImplService() {
        super(__getWsdlLocation(), STRINGCONVERSIONIMPLSERVICE_QNAME);
    }

    public StringConversionImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STRINGCONVERSIONIMPLSERVICE_QNAME, features);
    }

    public StringConversionImplService(URL wsdlLocation) {
        super(wsdlLocation, STRINGCONVERSIONIMPLSERVICE_QNAME);
    }

    public StringConversionImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STRINGCONVERSIONIMPLSERVICE_QNAME, features);
    }

    public StringConversionImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StringConversionImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StringConversion
     */
    @WebEndpoint(name = "StringConversionImplPort")
    public StringConversion getStringConversionImplPort() {
        return super.getPort(new QName("http://ejercicio2_2/", "StringConversionImplPort"), StringConversion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StringConversion
     */
    @WebEndpoint(name = "StringConversionImplPort")
    public StringConversion getStringConversionImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ejercicio2_2/", "StringConversionImplPort"), StringConversion.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STRINGCONVERSIONIMPLSERVICE_EXCEPTION!= null) {
            throw STRINGCONVERSIONIMPLSERVICE_EXCEPTION;
        }
        return STRINGCONVERSIONIMPLSERVICE_WSDL_LOCATION;
    }

}
